# Generated by Django 5.1.15 on 2026-05-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nomi')),
                ('code', models.CharField(help_text='Qisqa identifikator, masalan: yunusobod', max_length=20, unique=True, verbose_name='Kod')),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Markaz kenglik (latitude)')),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Markaz uzunlik (longitude)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DistrictBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Uzunlik')),
                ('order', models.PositiveIntegerField(default=0, help_text='Polygon nuqtalarining ketma-ketligi', verbose_name='Tartib')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_points', to='districts.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Chegara nuqtasi',
                'verbose_name_plural': 'Chegara nuqtalari',
                'ordering': ['district', 'order'],
                'unique_together': {('district', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text="Telegram guruh chat_id (manfiy son bo'lishi mumkin)", verbose_name='Chat ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Guruh nomi')),
                ('is_primary', models.BooleanField(default=False, help_text="Bir tumanda bitta asosiy guruh bo'lishi kerak", verbose_name='Asosiy guruh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_groups', to='districts.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Telegram guruh',
                'verbose_name_plural': 'Telegram guruhlar',
                'ordering': ['district', '-is_primary', 'name'],
                'unique_together': {('district', 'chat_id')},
            },
        ),
    ]
