# Generated by Django 5.1.15 on 2026-05-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, db_index=True, help_text='Tashqi servisdan kelgan noyob identifikator', max_length=128, verbose_name='Tashqi manba ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Uzunlik')),
                ('device_info', models.CharField(blank=True, max_length=255, verbose_name='Qurilma')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('distance_to_district_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Tumanga masofa (km)')),
                ('match_method', models.CharField(blank=True, max_length=32, verbose_name='Aniqlash usuli')),
                ('is_inside_boundary', models.BooleanField(default=False, verbose_name='Chegara ichida')),
                ('status', models.CharField(choices=[('received', 'Qabul qilindi'), ('routed', "Tumanga yo'naltirildi"), ('sent', 'Telegramga yuborildi'), ('failed', 'Xato'), ('no_district', 'Tuman topilmadi'), ('no_group', 'Guruh topilmadi')], db_index=True, default='received', max_length=20, verbose_name='Holat')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Yuborilgan chat ID')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram xabar ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Xato xabari')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Tashqi payload')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Qabul vaqti')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlov vaqti')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('assigned_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='districts.district', verbose_name='Tayinlangan tuman')),
            ],
            options={
                'verbose_name': 'SOS xabar',
                'verbose_name_plural': 'SOS xabarlar',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at', 'status'], name='sos_sosaler_receive_28b95f_idx')],
            },
        ),
    ]
