# Generated by Django 5.1.15 on 2026-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='source_telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Foydalanuvchi location yuborgan chat', null=True, verbose_name='Tashqi bot — chat ID'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='source_telegram_first_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tashqi bot — ism'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='source_telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tashqi bot — xabar ID'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='source_telegram_user_id',
            field=models.BigIntegerField(blank=True, help_text='Location yuborgan foydalanuvchi Telegram ID', null=True, verbose_name='Tashqi bot — user ID'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='source_telegram_username',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tashqi bot — username'),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, help_text='Tashqi Telegram bot xabari noyob identifikatori', max_length=128, verbose_name='Tashqi manba ID'),
        ),
    ]
